version: '3.8'  # Use a version of Docker Compose that's compatible with your Docker Engine

services:
  your-service:
    image: mg_ex
    deploy:
      resources:
        limits:
          cpus: '12.0'
          memory: 32000M
  jupyterlab:
    build:
      context: .  # Indicates the Dockerfile is in the same directory as this file
      target: runner  # Specifies which stage to build to for multi-stage builds
    ports:
      - "8888:8888"  # Maps port 8888 on the container to port 8888 on the host
    volumes:
      - .:/app  # Optional: Mounts the current directory on the host into /app in the container
    environment:
      - NAME=World  # Environment variables
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
      # Command to start Jupyter Lab


